version: '3.2'

services:
  sonarr:
    image: linuxserver/sonarr
    deploy:
      replicas: 1
    ports:
      - "8989:8989"
    volumes:
      - sonarr:/config
      - downloads:/downloads
      - tv:/tv
    environment:
      TZ: America/Edmonton
  
  radarr:
    image: linuxserver/radarr
    deploy:
      replicas: 1
    ports:
      - "7878:7878"
    volumes:
      - radarr:/config
      - downloads:/downloads
      - movies:/movies
    environment:
      TZ: America/Edmonton
  
  jackett:
    image: linuxserver/jackett
    deploy:
      replicas: 1
    ports:
      - "9117:9117"
    volumes:
      - jackett:/config
      - downloads:/downloads
    environment:
      TZ: America/Edmonton

volumes:
  sonarr:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/docker/sonarr
  radarr:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/docker/radarr
  jackett:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/docker/jackett
  downloads:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/downloads
  movies:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/vault/Movies
  tv:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/vault/TV
