version: '3.2'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  portainer-data:
    driver: nfs
    driver_opts:
      share: 10.0.0.35:/mnt/tank/docker/portainer-data
